version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "generate-email"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1s14ao5qfzhid"
s3_prefix = "generate-email"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EmailTemplateBucketStackName=\"email-template-bucket\" PersonTableStackName=\"personTable\""
