AWSTemplateFormatVersion: 2010-09-09
Description: >-
  generate-email-template

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  EmailTemplateBucketStackName:
    Description: Name of Bucket email template Stack
    Type: String
  PersonTableStackName:
    Description: Name of DynamoDB person Stack
    Type: String

Globals:
  Function:
    Environment:
      Variables:
        BUCKET_NAME:
          Fn::ImportValue: !Sub ${EmailTemplateBucketStackName}:EmailTemplateBucket

Resources:
  DynamoStreamEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function.
      Runtime: nodejs12.x
      Handler: src/handlers/dynamo-event-logger.DynamoStreamEventLoggerHandler
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaDynamoDBExecutionRole
        - S3FullAccessPolicy:
            BucketName:
              Fn::ImportValue: !Sub ${EmailTemplateBucketStackName}:EmailTemplateBucket
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue
              'Fn::Sub': ${PersonTableStackName}:personTableStreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
      MemorySize: 128
      Timeout: 600
